"use client";

/**
 * The fake backend.
 *
 * This file is the *only* difference in substance between this demo folder and
 * the real TeleCollect frontend: instead of a FastAPI server, every read is
 * answered from an in-memory store and every write mutates that store.  The
 * pages and components are untouched copies, which is what makes the demo an
 * honest preview of the real UI rather than a separate mock-up that drifts.
 *
 * Two design choices worth knowing about:
 *
 * * The seed data is generated by a *deterministic* PRNG, so the numbers on
 *   screen are the same on every machine and every reload.  A demo that
 *   reshuffles itself is impossible to screenshot or to talk through.
 * * Long-running jobs (training, evaluation) are not simulated with timers.
 *   Their status and metrics are *derived from elapsed wall time* since they
 *   were started, so they keep progressing correctly even if the tab is
 *   backgrounded or the page is remounted, and they survive a reload.
 */

import type {
  DatasetExport,
  Demo,
  DemoStatus,
  EvalRun,
  LabelValue,
  Role,
  RunStatus,
  Summary,
  Task,
  Trajectory,
  TrainingRun,
  User,
} from "./api";

// ---------------------------------------------------------------------------
// deterministic randomness
// ---------------------------------------------------------------------------

/** mulberry32 — small, fast, and identical in every browser. */
function rng(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Stable 32-bit hash, so a demo id always produces the same trajectory. */
function hash(text: string) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i += 1) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function pick<T>(random: () => number, items: readonly T[]): T {
  return items[Math.floor(random() * items.length)];
}

// ---------------------------------------------------------------------------
// seed content
// ---------------------------------------------------------------------------

export const TASKS: Task[] = [
  {
    id: "pick_place",
    title: "Pick and place",
    instruction: "Pick up the red cube and place it on the green target zone.",
    max_steps: 600,
    hints: [
      "Open the gripper before descending.",
      "Release the cube inside the green circle and lift away.",
    ],
  },
  {
    id: "stack",
    title: "Stack two cubes",
    instruction: "Stack the red cube on top of the blue cube.",
    max_steps: 700,
    hints: [
      "Grasp the red cube across its narrow face.",
      "Centre it over the blue cube before opening the gripper.",
    ],
  },
  {
    id: "push",
    title: "Push to target",
    instruction: "Push the yellow block into the marked target area.",
    max_steps: 500,
    hints: [
      "Keep the gripper closed and approach from behind the block.",
      "Push slowly — a fast contact makes the block spin away.",
    ],
  },
];

const SEED_USERS: Array<Omit<User, "created_at"> & { days: number }> = [
  {
    id: "u-operator",
    username: "operator",
    display_name: "Demo Operator",
    role: "operator",
    is_active: true,
    days: 42,
  },
  {
    id: "u-reviewer",
    username: "reviewer",
    display_name: "Demo Reviewer",
    role: "reviewer",
    is_active: true,
    days: 42,
  },
  {
    id: "u-admin",
    username: "admin",
    display_name: "Demo Admin",
    role: "admin",
    is_active: true,
    days: 42,
  },
  {
    id: "u-linh",
    username: "linh",
    display_name: "Linh Pham",
    role: "operator",
    is_active: true,
    days: 21,
  },
  {
    id: "u-tuan",
    username: "tuan",
    display_name: "Tuan Vo",
    role: "operator",
    is_active: false,
    days: 9,
  },
];

const DAY = 86_400_000;

// ---------------------------------------------------------------------------
// the store
// ---------------------------------------------------------------------------

export interface Store {
  users: User[];
  demos: Demo[];
  exports: DatasetExport[];
  runs: TrainingRun[];
  evals: EvalRun[];
}

const STORAGE_KEY = "telecollect.demo.store.v1";

function buildStore(): Store {
  const now = Date.now();
  const random = rng(20240815);

  const users: User[] = SEED_USERS.map(({ days, ...user }) => ({
    ...user,
    created_at: new Date(now - days * DAY).toISOString(),
  }));
  const operators = users.filter((u) => u.role !== "reviewer");

  const demos: Demo[] = [];
  for (let i = 0; i < 46; i += 1) {
    const task = pick(random, TASKS);
    const operator = pick(random, operators);
    const reviewer = users[1];
    const numFrames = 190 + Math.floor(random() * 380);
    const autoSuccess = random() < 0.72;

    // Age spreads over three weeks, newest first, so "recent" lists and
    // relative timestamps in the UI look like a real collection campaign.
    const created = new Date(now - i * 9.4 * 3600_000 - random() * 3600_000);

    // Most old recordings have been through review; the newest ones have not,
    // which is what gives the review queue something to work on.
    let status: DemoStatus = "recorded";
    let label: LabelValue | null = null;
    let reviewed = false;
    if (i >= 8) {
      reviewed = true;
      label = autoSuccess && random() < 0.9 ? "success" : "failure";
      status = label === "success" && random() < 0.88 ? "approved" : "rejected";
    }

    const p50 = 34 + random() * 26;
    demos.push({
      id: `demo-${String(i + 1).padStart(3, "0")}`,
      task_id: task.id,
      operator_id: operator.id,
      operator_name: operator.display_name,
      created_at: created.toISOString(),
      seed: 10_000 + Math.floor(random() * 89_999),
      fps: 30,
      num_frames: numFrames,
      duration_s: numFrames / 30,
      size_bytes: Math.round(numFrames * (5_400 + random() * 2_600)),
      auto_success: autoSuccess,
      auto_success_frame: autoSuccess ? Math.floor(numFrames * (0.62 + random() * 0.3)) : null,
      latency_p50_ms: p50,
      latency_p95_ms: p50 + 12 + random() * 30,
      control_jitter_ms: 0.8 + random() * 2.6,
      dropped_frames: random() < 0.8 ? 0 : Math.floor(random() * 5),
      status,
      label,
      trim_start: 0,
      trim_end: null,
      review_notes: reviewed && random() < 0.35 ? "Clean grasp, no regrasp attempts." : "",
      reviewer_id: reviewed ? reviewer.id : null,
      reviewer_name: reviewed ? reviewer.display_name : null,
      reviewed_at: reviewed ? new Date(created.getTime() + 3 * 3600_000).toISOString() : null,
    });
  }

  const approved = demos.filter((d) => d.status === "approved" && d.label === "success");
  const exportFrames = approved.reduce((sum, d) => sum + d.num_frames, 0);

  const exports: DatasetExport[] = [
    {
      id: "exp-001",
      name: "v1",
      format: "lerobot",
      created_at: new Date(now - 3 * DAY).toISOString(),
      tasks: [],
      include_failures: false,
      num_episodes: approved.length,
      num_frames: exportFrames,
      size_bytes: exportFrames * 6_100,
      path: "data/exports/v1",
      dvc_hash: "9f1c4b7e2a6d05c38e4417ab9c2f6d81",
      status: "ready",
      data_source: "both",
      collection_batch_id: null,
      created_by: "demo-admin",
      exporter_version: "1.0",
    },
    {
      id: "exp-002",
      name: "pick-place-only",
      format: "lerobot",
      created_at: new Date(now - 26 * 3600_000).toISOString(),
      tasks: ["pick_place"],
      include_failures: false,
      num_episodes: approved.filter((d) => d.task_id === "pick_place").length,
      num_frames: approved
        .filter((d) => d.task_id === "pick_place")
        .reduce((sum, d) => sum + d.num_frames, 0),
      size_bytes:
        approved
          .filter((d) => d.task_id === "pick_place")
          .reduce((sum, d) => sum + d.num_frames, 0) * 6_100,
      path: "data/exports/pick-place-only",
      dvc_hash: "3ba0e51d7c9482f6015d7ee4a8b3c020",
      status: "ready",
      data_source: "teleop",
      collection_batch_id: null,
      created_by: "demo-admin",
      exporter_version: "1.0",
    },
    {
      id: "exp-003",
      name: "v1-rlds",
      format: "rlds",
      created_at: new Date(now - 2 * DAY).toISOString(),
      tasks: [],
      include_failures: false,
      num_episodes: approved.length,
      num_frames: exportFrames,
      size_bytes: exportFrames * 5_400,
      path: "data/exports/v1-rlds",
      dvc_hash: null,
      status: "ready",
      data_source: "both",
      collection_batch_id: null,
      created_by: "demo-admin",
      exporter_version: "1.0",
    },
  ];

  const runs: TrainingRun[] = [
    {
      id: "run-001",
      name: "bc-v1",
      export_id: "exp-001",
      created_at: new Date(now - 2 * DAY).toISOString(),
      status: "succeeded",
      config: {
        export_name: "v1",
        steps: 8000,
        batch_size: 48,
        chunk_size: 16,
        image_size: 112,
        learning_rate: 0.0001,
        dvc_hash: "9f1c4b7e2a6d05c38e4417ab9c2f6d81",
      },
      metrics: {
        best_val_l1: 0.0417,
        num_episodes: approved.length,
        num_frames: exportFrames,
        train_seconds: 1_284,
        device: "cuda",
      },
      output_dir: "data/runs/bc-v1",
      error: "",
      finished_at: new Date(now - 2 * DAY + 1_284_000).toISOString(),
    },
    {
      id: "run-002",
      name: "bc-v1-chunk32",
      export_id: "exp-001",
      created_at: new Date(now - 20 * 3600_000).toISOString(),
      status: "succeeded",
      config: {
        export_name: "v1",
        steps: 12000,
        batch_size: 32,
        chunk_size: 32,
        image_size: 112,
        learning_rate: 0.0001,
      },
      metrics: {
        best_val_l1: 0.0388,
        num_episodes: approved.length,
        num_frames: exportFrames,
        train_seconds: 2_016,
        device: "cuda",
      },
      output_dir: "data/runs/bc-v1-chunk32",
      error: "",
      finished_at: new Date(now - 20 * 3600_000 + 2_016_000).toISOString(),
    },
    {
      id: "run-003",
      name: "bc-pickplace",
      export_id: "exp-002",
      created_at: new Date(now - 5 * 3600_000).toISOString(),
      status: "failed",
      config: {
        export_name: "pick-place-only",
        steps: 8000,
        batch_size: 96,
        chunk_size: 16,
        image_size: 224,
      },
      metrics: {},
      output_dir: "data/runs/bc-pickplace",
      error:
        "torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.94 GiB\n" +
        "Hint: batch_size 96 at image_size 224 needs ~9 GiB; drop one of the two.",
      finished_at: new Date(now - 5 * 3600_000 + 94_000).toISOString(),
    },
  ];

  const evals: EvalRun[] = [
    makeEval("eval-001", "run-001", "pick_place", 25, 0.72, now - 2 * DAY + 3_600_000),
    makeEval("eval-002", "run-001", "stack", 25, 0.44, now - 2 * DAY + 4_200_000),
    makeEval("eval-003", "run-002", "pick_place", 50, 0.80, now - 19 * 3600_000),
  ];

  return { users, demos, exports, runs, evals };
}

function makeEval(
  id: string,
  trainingRunId: string,
  taskId: string,
  numEpisodes: number,
  successRate: number,
  createdMs: number,
): EvalRun {
  const random = rng(hash(id));
  const episodes = Array.from({ length: numEpisodes }, (_, index) => {
    const success = random() < successRate;
    return {
      seed: 10_000 + index,
      success,
      steps: success ? 180 + Math.floor(random() * 120) : 500,
    };
  });
  const hits = episodes.filter((e) => e.success);
  const rate = hits.length / episodes.length;
  // Wilson-ish interval, wide enough to be honest about 25 episodes.
  const halfWidth = 1.96 * Math.sqrt((rate * (1 - rate)) / episodes.length);

  return {
    id,
    training_run_id: trainingRunId,
    created_at: new Date(createdMs).toISOString(),
    status: "succeeded",
    task_id: taskId,
    num_episodes: numEpisodes,
    success_rate: rate,
    mean_episode_length:
      episodes.reduce((sum, e) => sum + e.steps, 0) / episodes.length,
    details: {
      episodes,
      record_videos: 3,
      seed_range: [10_000, 10_000 + numEpisodes - 1],
      success_rate_ci95: [Math.max(0, rate - halfWidth), Math.min(1, rate + halfWidth)],
      mean_success_length: hits.length
        ? hits.reduce((sum, e) => sum + e.steps, 0) / hits.length
        : 0,
    },
    error: "",
    finished_at: new Date(createdMs + 240_000).toISOString(),
  };
}

// ---------------------------------------------------------------------------
// persistence
// ---------------------------------------------------------------------------

let store: Store | null = null;

export function db(): Store {
  if (store) return store;
  if (typeof window !== "undefined") {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved) {
      try {
        store = JSON.parse(saved) as Store;
        return store;
      } catch {
        /* corrupt or from an older version — fall through and rebuild */
      }
    }
  }
  store = buildStore();
  save();
  return store;
}

export function save() {
  if (typeof window === "undefined" || !store) return;
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(store));
  } catch {
    /* private mode / quota — the demo still works, it just will not persist */
  }
}

/** Throw the demo state away and rebuild the seed data. */
export function resetDemoData() {
  store = null;
  if (typeof window !== "undefined") window.localStorage.removeItem(STORAGE_KEY);
  db();
}

// Handy while showing the demo: `__telecollectDemo.reset()` in the console.
if (typeof window !== "undefined") {
  (window as unknown as Record<string, unknown>).__telecollectDemo = {
    reset: () => {
      resetDemoData();
      window.location.reload();
    },
    store: db,
  };
}

// ---------------------------------------------------------------------------
// derived data
// ---------------------------------------------------------------------------

export function summarise(): Summary {
  const demos = db().demos;
  const byStatus: Record<string, number> = {};
  const byLabel: Record<string, number> = {};
  const byTask: Record<string, Record<string, number>> = {};

  for (const demo of demos) {
    byStatus[demo.status] = (byStatus[demo.status] ?? 0) + 1;
    if (demo.label) byLabel[demo.label] = (byLabel[demo.label] ?? 0) + 1;
    const bucket = (byTask[demo.task_id] ??= {
      total: 0,
      success: 0,
      approved: 0,
      rejected: 0,
    });
    bucket.total += 1;
    if (demo.label === "success") bucket.success += 1;
    if (demo.status === "approved") bucket.approved += 1;
    if (demo.status === "rejected") bucket.rejected += 1;
  }

  const labelled = (byLabel.success ?? 0) + (byLabel.failure ?? 0);
  const reviewed = (byStatus.approved ?? 0) + (byStatus.rejected ?? 0);
  const valid = demos.filter((d) => d.status === "approved" && d.label === "success");
  const frames = demos.reduce((sum, d) => sum + d.num_frames, 0);
  const latencies = demos.map((d) => d.latency_p50_ms).sort((a, b) => a - b);

  return {
    total: demos.length,
    by_status: byStatus,
    by_label: byLabel,
    by_task: byTask,
    approved_successes: valid.length,
    valid_demo_count: valid.length,
    success_rate: labelled ? (byLabel.success ?? 0) / labelled : 0,
    approval_rate: reviewed ? (byStatus.approved ?? 0) / reviewed : 0,
    total_frames: frames,
    total_hours: frames / 30 / 3600,
    total_size_bytes: demos.reduce((sum, d) => sum + d.size_bytes, 0),
    median_latency_ms: latencies[Math.floor(latencies.length / 2)] ?? 0,
    p95_latency_ms: latencies[Math.floor(latencies.length * 0.95)] ?? 0,
  };
}

/**
 * A plausible trajectory for one recording.
 *
 * Shaped rather than random: the arm reaches, closes the gripper, transports,
 * releases, so the per-joint charts and the success band on the review timeline
 * tell the same story the video does.
 */
export function trajectoryFor(demo: Demo, stride = 1): Trajectory {
  const random = rng(hash(demo.id));
  const n = demo.num_frames;
  const successFrom = demo.auto_success_frame ?? n + 1;

  const state: number[][] = [];
  const action: number[][] = [];
  const eePose: number[][] = [];
  const success: boolean[] = [];
  const cmdAge: number[] = [];
  const rtt: number[] = [];
  const tickDt: number[] = [];

  const phaseGrasp = Math.floor(n * 0.35);
  const phaseLift = Math.floor(n * 0.5);
  const phaseRelease = Math.floor(n * 0.85);

  for (let i = 0; i < n; i += stride) {
    const t = i / n;
    const noise = () => (random() - 0.5) * 0.01;

    const joints = [
      0.5 * Math.sin(t * Math.PI * 0.9) + noise(),
      -0.4 + 0.9 * Math.sin(t * Math.PI) + noise(),
      0.9 - 0.5 * Math.sin(t * Math.PI * 1.2) + noise(),
      noise(),
      1.2 + 0.35 * Math.sin(t * Math.PI * 1.6) + noise(),
      noise(),
    ];
    const grip = i < phaseGrasp ? 1 : i < phaseRelease ? 0.24 : 1;

    state.push([...joints, grip]);
    action.push([...joints.map((v) => v + noise() * 0.4), grip]);

    const z =
      i < phaseGrasp
        ? 0.22 - 0.17 * (i / phaseGrasp)
        : i < phaseLift
          ? 0.05 + 0.16 * ((i - phaseGrasp) / (phaseLift - phaseGrasp))
          : i < phaseRelease
            ? 0.21
            : 0.06;
    eePose.push([
      0.3 + 0.12 * t + noise(),
      -0.1 + 0.2 * t + noise(),
      z + noise(),
      0,
      0,
      1,
      0,
    ]);

    success.push(i >= successFrom);
    cmdAge.push(4 + random() * 9);
    rtt.push(demo.latency_p50_ms + (random() - 0.4) * 18);
    tickDt.push(33.3 + (random() - 0.5) * demo.control_jitter_ms * 2);
  }

  return {
    num_frames: n,
    fps: demo.fps,
    trim_start: demo.trim_start,
    trim_end: demo.trim_end ?? n,
    state,
    action,
    ee_pose: eePose,
    success,
    cmd_age_ms: cmdAge,
    rtt_ms: rtt,
    tick_dt_ms: tickDt,
  };
}

// ---------------------------------------------------------------------------
// jobs: status derived from elapsed time, never from a timer
// ---------------------------------------------------------------------------

/** How long a freshly started demo job pretends to take. */
export const TRAIN_DURATION_MS = 45_000;
export const EVAL_DURATION_MS = 15_000;

function elapsed(createdAt: string) {
  return Date.now() - new Date(createdAt).getTime();
}

/** Progress in 0..1 of a job that was started inside this demo session. */
export function jobProgress(createdAt: string, durationMs: number) {
  return Math.min(1, Math.max(0, elapsed(createdAt) / durationMs));
}

export function liveRunStatus(run: TrainingRun): RunStatus {
  if (!run.config.__demo_live) return run.status;
  return jobProgress(run.created_at, TRAIN_DURATION_MS) >= 1 ? "succeeded" : "running";
}

export function runHistoryFor(run: TrainingRun): Record<string, number>[] {
  const steps = Number(run.config.steps ?? 8000);
  const live = Boolean(run.config.__demo_live);
  const fraction = live ? jobProgress(run.created_at, TRAIN_DURATION_MS) : 1;
  if (run.status === "failed") return [];

  const random = rng(hash(run.id));
  const points = Math.max(1, Math.round(60 * fraction));
  const history: Record<string, number>[] = [];
  for (let i = 1; i <= points; i += 1) {
    const step = Math.round((i / 60) * steps);
    // Exponential decay towards a floor, plus a little noise: the shape of a
    // behaviour-cloning L1 curve that is actually converging.
    const base = 0.028 + 0.22 * Math.exp(-3.1 * (i / 60));
    history.push({ step, train_l1: base + (random() - 0.5) * 0.006 });
    if (i % 5 === 0) {
      history.push({ step, val_l1: base * 1.14 + (random() - 0.5) * 0.008 });
    }
  }
  return history;
}

export function runLogFor(run: TrainingRun): string {
  const history = runHistoryFor(run);
  const lines = [
    `[00:00:00] loading dataset ${String(run.config.export_name ?? "")}`,
    `[00:00:04] ${run.metrics?.num_episodes ?? "?"} episodes / ${
      run.metrics?.num_frames ?? "?"
    } frames, 90/10 episode-level split`,
    `[00:00:05] policy: ResNet18 backbone, action chunk ${String(run.config.chunk_size)}`,
    `[00:00:06] device=cuda amp=on batch=${String(run.config.batch_size)}`,
  ];
  for (const row of history) {
    if (row.train_l1 === undefined) continue;
    lines.push(`[step ${String(row.step).padStart(6)}] train_l1=${row.train_l1.toFixed(4)}`);
  }
  if (run.status === "failed") lines.push("", run.error ?? "Training failed");
  else if (liveRunStatus(run) === "succeeded") {
    lines.push(`[done] best val_l1=${Number(run.metrics?.best_val_l1 ?? 0).toFixed(4)}`);
  }
  return lines.slice(-40).join("\n");
}

export function liveEval(item: EvalRun): EvalRun {
  if (!item.details?.__demo_live) return item;
  if (jobProgress(item.created_at, EVAL_DURATION_MS) < 1) {
    return { ...item, status: "running" };
  }
  const finished = makeEval(
    item.id,
    item.training_run_id,
    item.task_id,
    item.num_episodes,
    0.68,
    new Date(item.created_at).getTime(),
  );
  return finished;
}

// ---------------------------------------------------------------------------
// ids
// ---------------------------------------------------------------------------

let counter = 0;
export function newId(prefix: string) {
  counter += 1;
  return `${prefix}-${Date.now().toString(36)}${counter.toString(36)}`;
}

export function roleFor(username: string): Role {
  const name = username.toLowerCase();
  if (name.includes("admin")) return "admin";
  if (name.includes("review")) return "reviewer";
  return "operator";
}
